# Generated by Django 6.1 on 2026-08-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('accessories', 'Accessories'), ('apparel', 'Apparel'), ('home', 'Home & Kitchen'), ('fitness', 'Fitness')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='comma separated keywords', max_length=300)),
                ('stock', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
