# Generated by Django 6.1 on 2026-08-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('cart_snapshot', models.JSONField()),
                ('cart_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('likely_reason', models.CharField(max_length=100)),
                ('recovery_message', models.TextField()),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('raw_model_output', models.TextField()),
                ('recovered', models.BooleanField(default=False)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
